version: '2'
services:
  clickhouse_db:
    image: bitnami/clickhouse:latest
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - CLICKHOUSE_ADMIN_PASSWORD=admin
      - CLICKHOUSE_ADMIN_USER=default
      - CLICKHOUSE_HTTP_PORT=9123
    network_mode: host

  mysql_db:
    image: mysql/mysql-server:8.0.32
    environment:
      - MYSQL_DATABASE=admin
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=admin
    networks:
      default:
    ports:
      - 9306:3306
    volumes:
      - ./test_mysql.cnf:/etc/my.cnf:ro

  replicator:
    image: python:3.12.4-slim-bookworm
    command: bash -c "pip install -r /app/requirements.txt && tail -f /dev/null"
    network_mode: host
    volumes:
      - ./:/app/
